### ISSUE TITLE
Use of deprecated NodeJS version

### ISSUE THREAD

**Issue by chizhonkova** [yc-actions/yc-github-runner#261]
Using this action, GitHub actions complains about the deprecated NodeJS version 16.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/. 
Please, update this action to version 20.

**Comment by chizhonkova** [comment]
Thank you! Can you tell a ETA for the release with this feature?

**Comment by nikolaymatrosov** [comment]
It should already be released. Just after the issue was closed.
